### ISSUE TITLE
Review parts for Alpha prototype

### ISSUE THREAD

**Issue by Burhan-Q** [helpfulengineering/project-tetra#120]
All parts, components, and assemblies need to be reviewed and verified as ready

- [ ] List parts not yet produced in comment below, include issue number where applicable, provide additional details as needed
- [ ] List parts still being revised in comment below, include issue number where applicable, provide additional details as needed
- [ ] Verify that all off-the-shelf components have been ordered and are on hand, comment with any that are missing
- [ ] Establish plan to address outstanding concerns/problems over (at least) the next week

**Comment by Burhan-Q** [comment]
## Parts not yet made: ##

- [ ] P-TET-000025-0 **Inspiratory bias**
    - [x] part development work in progress
    - [ ] ready to print 🤷 [STATUS UNKNOWN]
    - [ ] sent for print testing
    - [ ] ready for release
- [ ] P-TET-000026-0 **Expiratory bias**
    - [x] part development work in progress
    - [ ] ready to print 🤷 [STATUS UNKNOWN]
    - [ ] sent for print testing
    - [ ] ready for release
- [ ] P-TET-000029-0 **Sensirion comm PCB** #113 & #114 
     - [x] components ordered, shipping
     - [ ] parts assembled
     - [ ] ready for use and/or testing

**Comment by Burhan-Q** [comment]
## Parts under revision: ##

- [ ] P-TET-000030 **Tetra valve core** #99 
    - [x] part development work in progress
    - [x] ready to print
    - [x] sent for print testing
    - [ ] ready for release
- [ ] P-TET-000031 **Tetra valve knob** #99 
    - [x] part development work in progress
    - [x] ready to print
    - [x] sent for print testing
    - [ ] ready for release
- [ ] P-TET-000027 **Sensirion cable harness** #67 
    - [x] part development work in progress
    - [x] ready to print
    - [x] sent for print testing
    - [ ] ready for release
- [ ] P-TET-000018 **Shutoff valve main body** #104 
    - [x] part development work in progress
    - [x] ready to print
    - [x] sent for print testing
    - [ ] ready for release
- [ ] P-TET-000019 **Shutoff valve thru body** #98 
    - [x] part development work in progress
    - [x] ready to print
    - [x] sent for print testing
    - [ ] ready for release
- [ ] P-TET-000004-0 RPi display frame #64 
    - [x] part development work in progress
    - [x] ready to print
    - [x] sent for print testing
    - [ ] ready for release

**Comment by Burhan-Q** [comment]
## Missing off-the-shelf-parts: ##
- [ ]

**Comment by Burhan-Q** [comment]
Shared by @mechatroniks-git via slack

- [ ] 1. Rear Port Cover - needs part # and STL to test print. Will need 1 for build.
     (2020-08-14) blocked by bias components, @jgrano will design this once bias is ready

- [x] 2. P-TET-000019 - need to print one of -3 & test. Will need 8 for build.
     (2020-08-14) test version printed and delivered to patrick 

- [x] 3. P-TET-000021-2 - need print 8 for build. (Patrick to complete by 8/14)
     (2020-08-14) @mechatroniks-git currently printing
- [x] 4. P-TET-000020-2 - need to print 8 for build. (Patrick to complete by 8/14)
     (2020-08-14) @mechatroniks-git currently printing

- [ ] 5. P-TET-000018 - need to print one of -2 & test. Will need 8 for build.
     (2020-08-14) model updated and shared with @DHHwangPhD , part printed and getting ready to cure (should be ready Saturday)

- [ ] 6. P-TET-000006 - need to print one of -? & test. Will need 4 for build.
     (2020-08-14) @jgrano working on this, doing print tests and will send to @mechatroniks-git 

- [ ] 7. P-TET-000027 - need status? Will need 4 for build.
     (2020-08-14) @Burhan-Q been working with @fpdotmonkey to troubleshoot printing issues; PCB not fitting
     (2020-08-15) @fpdotmonkey resolve issues with printer, PCB fits, design changes needed

- [ ] 8. P-TET-000028 - may need to elongate one way disc nub? Will need 4 for build.
     (2020-08-14) @jgrano making adjustments to valve length, will print more and ship to @mechatroniks-git 

- [ ] 9. P-TET-000029 - Will need 4 for build.
     (2020-08-14) @fpdotmonkey has the parts for these, can build enough for next Friday

- [ ] 10. P-TET-000030-0 - Part good, need 4 for build.
     (2020-08-14) @mechatroniks-git made modifications to model; @DHHwangPhD printed and looks good and will print 3 more

- [ ] 11. P-TET-000031 - Design good, can reduce print mass. Will need 4 for build.
     (2020-08-14) reduction of mass can wait, @mechatroniks-git has eval unit, @DHHwangPhD printing 3 more 

- [ ] 12. P-TET-000025 - needs STL to print. Will need 1 for build
     (2020-08-14) @Burhan-Q working on this, @jgrano will print once ready

- [ ] 13. P-TET-000026 - needs STL to print. Will need 1 for build
     (2020-08-14) @Burhan-Q working on this, @jgrano will print once ready

**Comment by Burhan-Q** [comment]
UPDATE:

7. P-TET-000027 - need status? Will need 4 for build.
- printer issues resolved, PCB now fits
- @fpdotmonkey to print remaining parts needed to deliver to @mechatroniks-git 

 12. P-TET-000025 - needs STL to print. Will need 1 for build     
- Shared with @jgrano for printing on August 14     

 13. P-TET-000026 - needs STL to print. Will need 1 for build     
- Shared with @jgrano for printing August 14     

See printing log [here](https://docs.google.com/spreadsheets/d/1FWTYRxglWDqIK_xI6HlBGKUegICQRsXe5NHCJTlTlHs/edit#gid=563995584&range=A1)

**Comment by Burhan-Q** [comment]
Second sprint concluded. Parts shipping to or on premise with @mechatroniks-git for assembly and testing. This issue was created as a log and has no associated PR or commit.
